In [10]:
import dlt
from dlt.sources.helpers.rest_client import RESTClient
from dlt.sources.helpers.rest_client.paginators import PageNumberPaginator

pipeline = dlt.pipeline(
    pipeline_name = "api_ingestion_pipeline",
    destination = dlt.destinations.postgres("postgresql://kestra:k3str4@localhost:5431/postgres-zoomcamp"),
    dataset_name = "public"
)

def paginated_getter():
    client = RESTClient(
        base_url = "https://us-central1-dlthub-analytics.cloudfunctions.net",
        paginator = PageNumberPaginator(base_page=1, total_path=None)
    )
    for page in client.paginate("data_engineering_zoomcamp_api"):
        yield page

load_info = pipeline.run(paginated_getter(), table_name="api_table", write_disposition="replace")
print(load_info)

Pipeline api_ingestion_pipeline load step completed in 0.66 seconds
1 load package(s) were loaded to destination postgres and into dataset public
The postgres destination used postgresql://kestra:***@localhost:5431/postgres-zoomcamp location to store data
Load package 1739674431.4486053 is LOADED and contains no failed jobs

In [15]:
pipeline.dataset(dataset_type="default").api_table.df()

,end_lat,end_lon,fare_amt,passenger_count,payment_type,start_lat,start_lon,tip_amt,tolls_amt,total_amt,trip_distance,trip_dropoff_date_time,trip_pickup_date_time,surcharge,vendor_name,_dlt_load_id,_dlt_id,store_and_forward
0,40.742963,-73.980072,45.0,1,Credit,40.641525,-73.787442,9.0,4.15,58.15,17.52,2009-06-14 23:48:00+00:00,2009-06-14 23:23:00+00:00,0.0,VTS,1739674431.4486053,X1JCbUAt1LB1ZQ,NaN
1,40.740187,-74.005698,6.5,1,Credit,40.722065,-74.009767,1.0,0.00,8.50,1.56,2009-06-18 17:43:00+00:00,2009-06-18 17:35:00+00:00,1.0,VTS,1739674431.4486053,NqKATyrPyrGbYg,NaN
2,40.718043,-74.004745,12.5,5,Credit,40.761945,-73.983038,2.0,0.00,15.50,3.37,2009-06-10 18:27:00+00:00,2009-06-10 18:08:00+00:00,1.0,VTS,1739674431.4486053,xZw/K1gqFefW9A,NaN
3,40.739637,-73.985233,4.9,1,CASH,40.749802,-73.992247,0.0,0.00,5.40,1.11,2009-06-14 23:58:00+00:00,2009-06-14 23:54:00+00:00,0.5,VTS,1739674431.4486053,x1R+766UCQ4qnA,NaN
4,40.730032,-73.852693,25.7,1,CASH,40.776825,-73.949233,0.0,4.15,29.85,11.09,2009-06-13 13:23:00+00:00,2009-06-13 13:01:00+00:00,0.0,VTS,1739674431.4486053,GnA/oeWbl1ij3w,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,40.783522,-73.970690,5.7,1,CASH,40.778560,-73.953660,0.0,0.00,5.70,1.16,2009-06-19 11:28:00+00:00,2009-06-19 11:22:00+00:00,0.0,VTS,1739674431.4486053,COH5fCqPUfTREA,NaN
9996,40.777200,-73.964197,4.1,1,CASH,40.779800,-73.974297,0.0,0.00,4.10,0.89,2009-06-17 07:43:00+00:00,2009-06-17 07:41:00+00:00,0.0,VTS,1739674431.4486053,U4k+NX1XxriVGQ,NaN
9997,40.780172,-73.957617,6.1,1,CASH,40.788388,-73.976758,0.0,0.00,6.10,1.30,2009-06-19 11:46:00+00:00,2009-06-19 11:39:00+00:00,0.0,VTS,1739674431.4486053,3O+rxCDKA/aOkA,NaN
9998,40.777342,-73.957242,5.7,1,CASH,40.773828,-73.956690,0.0,0.00,6.20,0.97,2009-06-17 04:19:00+00:00,2009-06-17 04:13:00+00:00,0.5,VTS,1739674431.4486053,GYafFL0kLlZ7oQ,NaN
9999,40.757122,-73.986293,6.5,1,Credit,40.756313,-73.972948,2.0,0.00,8.50,0.92,2009-06-17 08:34:00+00:00,2009-06-17 08:24:00+00:00,0.0,VTS,1739674431.4486053,Ys6Dxbw4KqsPWw,NaN